apiVersion: v1
kind: Service
metadata:
  name: svc-drupal
  labels:
    app: drupal-app
spec:
  type: LoadBalancer
  selector:
    proyecto: drupal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-deployment
  labels:
    app: drupal-app
spec:
  selector:
    matchLabels:
      proyecto: drupal-app
  replicas: 1
  template:
    metadata:
      labels:
        proyecto: drupal-app
    spec:
      containers:
        - name: drupal_container
          image: hj3ric/drupal:v1
          ports:
            - containerPort: 80
          env:
            - name: DRUPAL_DB_HOST
              value: "svc-mysql"
            - name: DRUPAL_DB_NAME
              value: "drupal_db"
            - name: DRUPAL_DB_USER
              value: "drupal_user"
            - name: DRUPAL_DB_PASSWORD
              value: "asdf1234"