apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  labels:
    app: mysql-app
spec:
  type: LoadBalancer
  selector:
    proyecto: mysql-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-app
spec:
  selector:
    matchLabels:
      proyecto: mysql-app
  replicas: 1
  template:
    metadata:
      labels:
        proyecto: mysql-app
    spec:
      containers:
        - name: mysql_container
          image: hj3ric/mysql:v1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "asd123"
            - name: MYSQL_DATABASE
              value: "drupal_db"
            - name: MYSQL_USER
              value: "drupal_user"
            - name: MYSQL_PASSWORD
              value: "asdf1234"
          volumeMounts:
            - name: persistent-storage-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: persistent-storage-mysql
          persistentVolumeClaim:
            claimName: mysql-pvc